## WINDOW ##
SCREEN_WIDTH = 500
SCREEN_HEIGHT = 650 
FONT = 'freesansbold.ttf'
FONT_SIZE = 20

## PLAYER ##
PLAYER_SPAWN_X = 50 
PLAYER_SPAWN_Y = 50     
PLAYER_VELOCITY = 4  
PLAYER_WIDTH = 15      
PLAYER_HEIGHT = 15      
PLAYER_COLOUR = (255,0,0) 
PLAYER_BOOST = 25
PLAYER_BOOST_REGEN = 0.5
PLAYER_BOOST_DECAY = 1
PLAYER_LIVES = 3

## PELLETS ##
SPAWN_RATE = 0.9 # Lower number means higher spawn!
PELLET_VELOCITY = 7
PELLET_SIZE = 10

